### ISSUE TITLE
chrome version

### ISSUE THREAD

**Issue by EdStrickland** [SAP/devops-docker-node-browsers#27]
Hi team, any chance we could update the chrome version to 87  in this docker?

**Comment by fwilhe** [comment]
Hi,

we install chromium that is in the debian repos. The current version there is 83, cf https://packages.debian.org/buster/chromium

I don't see a simple way to update the version in this image. The version will be updated once debian stable has updated Chromium.

Out of curiosity: Any specific reason why you need a newer version? Any other images that satisfy your requirements?

**Comment by EdStrickland** [comment]
Hi,
No I only ask on my curiosity. However, since we are running E2E tests on this docker, I am thinking of the possiblilty that there may be some tests fails on older version of Chrom.

**Comment by fwilhe** [comment]
Ok.

The image is rebuilt on a regular basis (weekly for the `latest` tag), so once Debian manages to update chromium, it will be in this image. I don't know when this happens. If you _need_ a more recent version now, I'd recommend looking for another image or building your own.

Kind regards

Florian
